### PR TITLE
John4744/rtc build

### PR DESCRIPTION
**Pull request by john4744**
Issue: https://devtopia.esri.com/runtime/home-one/issues/471
Upgrading runtimecore's libpng version to 1.6.37. Some deviations here are:
- We've included an ifdef tweak to allow building for Win UWP as described here: https://sourceforge.net/p/libpng/feature-requests/31/
- NEON optimizations are disabled for ARM platforms. These optimizations weren't included in our previous versions of libpng, so we shouldn't see any performance degradation. But in the future we may want to try enabling these to gain a performance boost.
- I changed the way the symbol renaming works on iOS. the libPNG configuration scripts now provide a command line option (`--with-libpng-prefix=FOO_`) to automatically do the renaming. It does this by dumping all the redefines in pnglibconf.h and pngpriv.h. Since pnglibconf.h is shared between all platforms, I added an ifdef RTC_COCOA_IOS to enable it only for iOS.

/CC: @parkske

### CODE REVIEW

**Review by chri7325 — APPROVED** [review]
Very nice! Glad to see there's native support for symbol renaming and no need to hack it anymore.  We no longer need symbol renaming for our product but it is useful for the qml test app.

**Review by colingpowell — APPROVED** [review]
Good work!

**Comment by john4744** [comment]
> We no longer need symbol renaming for our product but it is useful for the qml test app.

Does iOS no longer release static libs?

**Comment by chri7325** [comment]
One request I do have is if the first commit message could be amended with instructions on how you generated the config files so it can be reproduced easily?

> Does iOS no longer release static libs?

We do but we prelink them all together.  Since we compile everything with hidden visibility, with the exception of the c_api, all symbols are completely hidden and no longer collide with any other projects.

**Pull request merged**
