### PR TITLE
Update v1.6.39

### PR DESCRIPTION
**Pull request by itrombley**
**Issue**
https://devtopia.esri.com/runtime/common/issues/13585

**3rdparty build**
https://runtime-rtc.esri.com/view/vTest/job/vtest/job/3rdparty-interface/346/downstreambuildview/

**Runtimecore build and test**
https://runtime-rtc.esri.com/view/vTest/job/vtest/job/runtimecore-interface/8065/downstreambuildview/

### CODE REVIEW

**Comment by chri7325** [comment]
@itrombley I don't see any of the generated files getting updated. See https://github.com/Esri/libpng/pull/1 for an example of the generated files. There could be some differences between the versions.

**Comment by itrombley** [comment]
It's just a bugfix release. I don't see how any of that would change.

**Comment by chri7325** [comment]
A lot of projects generate version information in these configs which later can get picked up by protocode and report the wrong version so they're generally important to run and update.

**Comment by itrombley** [comment]
I see what you're saying. I'll give it a go tomorrow.

**Comment by itrombley** [comment]
@chri7325 
I ran `./configure` and none of those files changed.

**Review by chri7325 — APPROVED** [review]
Looks good to me!

**Pull request merged**
